// ================================================================
// MEDIDAS DAX - credito_bba
// Dashboard de Credito Corporativo | layout atual do repositorio
//
// Destino recomendado:
//   tabela tecnica "_Medidas" no Power BI Desktop
//
// Fontes esperadas no modelo:
//   vw_stage_cliente_enriquecido
//   vw_stage_exposicao_recente
//   vw_stage_rating_recente
//   vw_stage_limite_consolidado
//   vw_stage_operacoes_ativas
//   vw_kpi_por_subsetor
//   vw_matriz_risco
//   vw_evolucao_rating_segmento
//   operacoes
//   ratings
//   dCalendario
//   dAgingVencimento (arquivo auxiliar em powerbi/dax/tabelas_suporte_dashboard.dax)
//
// Convencao:
//   comentarios "PASTA:" indicam o Display Folder sugerido
// ================================================================


// ================================================================
// PASTA: 0. Base
// ================================================================

Qtd Clientes Ativos =
CALCULATE(
    DISTINCTCOUNT( vw_stage_cliente_enriquecido[cliente_id] ),
    vw_stage_cliente_enriquecido[status_cliente] = "Ativo"
)

Qtd Clientes Selecionados =
DISTINCTCOUNT( vw_stage_cliente_enriquecido[cliente_id] )

Qtd Operacoes Ativas =
CALCULATE(
    COUNTROWS( operacoes ),
    operacoes[status_operacao] = "Ativa"
)

Qtd Operacoes Vencidas =
CALCULATE(
    COUNTROWS( operacoes ),
    operacoes[status_operacao] = "Vencida"
)

Qtd Ratings Registrados =
COUNTROWS( ratings )


// ================================================================
// PASTA: 1. Visao Geral
// ================================================================

Exposicao Total =
SUM( vw_stage_cliente_enriquecido[exposicao_total] )

Exposicao Garantida =
SUM( vw_stage_cliente_enriquecido[exposicao_garantida] )

Exposicao Descoberta =
SUM( vw_stage_cliente_enriquecido[exposicao_descoberta] )

Pct Exposicao Descoberta =
DIVIDE( [Exposicao Descoberta], [Exposicao Total] )

Score Medio =
ROUND( AVERAGE( vw_stage_cliente_enriquecido[score_interno] ), 0 )

// PD ponderada pela exposicao de cada cliente.
// Evita distorcao por clientes pequenos com PD elevada — metrica padrao para
// carteiras corporativas heterogeneas. Alinhado com pd_ponderado_pct nas views SQL.
PD Media Pct =
DIVIDE(
    SUMX(
        vw_stage_cliente_enriquecido,
        vw_stage_cliente_enriquecido[pd_12m] * vw_stage_cliente_enriquecido[exposicao_total]
    ),
    SUM( vw_stage_cliente_enriquecido[exposicao_total] )
) * 100

// Provisao regulatoria: taxa CMN 2.682 por faixa de rating aplicada sobre exposicao_total.
// Metodologia diferente do HTML (PD ponderada x descoberta) — ambas documentadas.
// Esta e a abordagem correta para contexto regulatorio / Power BI.
Provisao Total Estimada =
SUM( vw_stage_cliente_enriquecido[provisao_necessaria] )

Exposicao Total BI =
DIVIDE( [Exposicao Total], 1000000000 )

Provisao Total MM =
DIVIDE( [Provisao Total Estimada], 1000000 )


// ================================================================
// PASTA: 2. Aprof. KPIs
// ================================================================

Valor Vencido =
CALCULATE(
    SUM( operacoes[valor_utilizado] ),
    operacoes[status_operacao] = "Vencida"
)

Pct Carteira Vencida =
DIVIDE( [Valor Vencido], [Exposicao Total] )

Utilizacao Media Pct =
AVERAGE( vw_stage_cliente_enriquecido[pct_utilizacao_limite] )

Valor Top 5 Clientes =
VAR _baseClientes =
    ADDCOLUMNS(
        SUMMARIZE(
            vw_stage_cliente_enriquecido,
            vw_stage_cliente_enriquecido[cliente_id]
        ),
        "exp_cliente", CALCULATE( MAX( vw_stage_cliente_enriquecido[exposicao_total] ) )
    )
VAR _top5 =
    TOPN( 5, _baseClientes, [exp_cliente], DESC )
RETURN
    SUMX( _top5, [exp_cliente] )

Pct Top 5 Clientes =
DIVIDE( [Valor Top 5 Clientes], [Exposicao Total] )

Valor Restante Carteira =
[Exposicao Total] - [Valor Top 5 Clientes]

Utilizacao Media por Segmento Pct =
AVERAGE( vw_stage_cliente_enriquecido[pct_utilizacao_limite] )

Valor Vencido Aging =
VAR _faixa = SELECTEDVALUE( dAgingVencimento[Faixa] )
RETURN
    SWITCH(
        _faixa,
        "1-30d",
            CALCULATE(
                SUM( operacoes[valor_utilizado] ),
                operacoes[status_operacao] = "Vencida",
                FILTER(
                    operacoes,
                    VAR _dias = DATEDIFF( operacoes[data_vencimento], TODAY(), DAY )
                    RETURN _dias >= 1 && _dias <= 30
                )
            ),
        "31-60d",
            CALCULATE(
                SUM( operacoes[valor_utilizado] ),
                operacoes[status_operacao] = "Vencida",
                FILTER(
                    operacoes,
                    VAR _dias = DATEDIFF( operacoes[data_vencimento], TODAY(), DAY )
                    RETURN _dias >= 31 && _dias <= 60
                )
            ),
        "61-90d",
            CALCULATE(
                SUM( operacoes[valor_utilizado] ),
                operacoes[status_operacao] = "Vencida",
                FILTER(
                    operacoes,
                    VAR _dias = DATEDIFF( operacoes[data_vencimento], TODAY(), DAY )
                    RETURN _dias >= 61 && _dias <= 90
                )
            ),
        "91-180d",
            CALCULATE(
                SUM( operacoes[valor_utilizado] ),
                operacoes[status_operacao] = "Vencida",
                FILTER(
                    operacoes,
                    VAR _dias = DATEDIFF( operacoes[data_vencimento], TODAY(), DAY )
                    RETURN _dias >= 91 && _dias <= 180
                )
            ),
        "180d+",
            CALCULATE(
                SUM( operacoes[valor_utilizado] ),
                operacoes[status_operacao] = "Vencida",
                FILTER(
                    operacoes,
                    DATEDIFF( operacoes[data_vencimento], TODAY(), DAY ) > 180
                )
            )
    )


// ================================================================
// PASTA: 3. Provisao e Classificacao
// ================================================================

Exposicao por Classificacao Risco =
[Exposicao Total]

Provisao por Segmento =
[Provisao Total Estimada]

Qtd Clientes por Classificacao Risco =
DISTINCTCOUNT( vw_stage_cliente_enriquecido[cliente_id] )


// ================================================================
// PASTA: 4. Evolucao e Distribuicao
// ================================================================

Score Medio Historico =
AVERAGE( vw_evolucao_rating_segmento[score_medio] )

Nota Media Historica =
AVERAGE( vw_evolucao_rating_segmento[nota_media] )

Score Medio Historico MM =
VAR _scoreAtual = [Score Medio Historico]
VAR _scoreAnterior =
    CALCULATE(
        [Score Medio Historico],
        DATEADD( dCalendario[Date], -1, MONTH )
    )
RETURN
    _scoreAtual - _scoreAnterior

Score Medio Historico Media Movel 3M =
AVERAGEX(
    DATESINPERIOD( dCalendario[Date], MAX( dCalendario[Date] ), -3, MONTH ),
    CALCULATE( [Score Medio Historico] )
)

Exposicao por Segmento =
[Exposicao Total]

Qtd Clientes por Rating =
DISTINCTCOUNT( vw_stage_cliente_enriquecido[cliente_id] )


// ================================================================
// PASTA: 5. Concentracao
// ================================================================

Pct Concentracao Subsetor =
DIVIDE(
    [Exposicao Total],
    CALCULATE(
        [Exposicao Total],
        ALL( vw_stage_cliente_enriquecido[subsetor] )
    )
)

Pct Concentracao Setor =
DIVIDE(
    [Exposicao Total],
    CALCULATE(
        [Exposicao Total],
        ALL( vw_stage_cliente_enriquecido[setor] )
    )
)

HHI Concentracao Carteira =
VAR _baseClientes =
    ADDCOLUMNS(
        SUMMARIZE(
            vw_stage_cliente_enriquecido,
            vw_stage_cliente_enriquecido[cliente_id]
        ),
        "exp_cliente", CALCULATE( MAX( vw_stage_cliente_enriquecido[exposicao_total] ) )
    )
RETURN
    SUMX(
        _baseClientes,
        POWER( DIVIDE( [exp_cliente], [Exposicao Total] ), 2 )
    )

Pct Top 10 Clientes =
VAR _baseClientes =
    ADDCOLUMNS(
        SUMMARIZE(
            vw_stage_cliente_enriquecido,
            vw_stage_cliente_enriquecido[cliente_id]
        ),
        "exp_cliente", CALCULATE( MAX( vw_stage_cliente_enriquecido[exposicao_total] ) )
    )
VAR _top10 =
    TOPN( 10, _baseClientes, [exp_cliente], DESC )
RETURN
    DIVIDE( SUMX( _top10, [exp_cliente] ), [Exposicao Total] )

Qtd Subsetores Limite Regulatorio =
CALCULATE(
    DISTINCTCOUNT( vw_kpi_por_subsetor[subsetor] ),
    vw_kpi_por_subsetor[status_concentracao] = "LIMITE_REGULATORIO"
)

Qtd Subsetores Monitoramento =
CALCULATE(
    DISTINCTCOUNT( vw_kpi_por_subsetor[subsetor] ),
    vw_kpi_por_subsetor[status_concentracao] = "MONITORAMENTO"
)


// ================================================================
// PASTA: 6. Analise de Riscos
// ================================================================

Qtd Clientes Alto Risco =
CALCULATE(
    DISTINCTCOUNT( vw_matriz_risco[cliente_id] ),
    vw_matriz_risco[classificacao_risco] = "ALTO_RISCO"
)

Qtd Clientes Atencao Risco =
CALCULATE(
    DISTINCTCOUNT( vw_matriz_risco[cliente_id] ),
    vw_matriz_risco[classificacao_risco] = "ATENCAO"
)

Qtd Clientes Normal Risco =
CALCULATE(
    DISTINCTCOUNT( vw_matriz_risco[cliente_id] ),
    vw_matriz_risco[classificacao_risco] = "NORMAL"
)

Exposicao Alto Risco =
CALCULATE(
    SUM( vw_matriz_risco[exposicao_total] ),
    vw_matriz_risco[classificacao_risco] = "ALTO_RISCO"
)

Pct Carteira Alto Risco =
DIVIDE( [Exposicao Alto Risco], [Exposicao Total] )

Total Flags de Risco =
SUMX(
    vw_matriz_risco,
    vw_matriz_risco[flag_deterioracao_rating]
    + vw_matriz_risco[flag_utilizacao_alta]
    + vw_matriz_risco[flag_descoberta_alta]
)

Score de Risco Combinado =
AVERAGEX(
    vw_matriz_risco,
    vw_matriz_risco[flag_deterioracao_rating]
    + vw_matriz_risco[flag_utilizacao_alta]
    + vw_matriz_risco[flag_descoberta_alta]
)

Qtd Clientes Deterioracao Rating =
CALCULATE(
    DISTINCTCOUNT( vw_matriz_risco[cliente_id] ),
    vw_matriz_risco[flag_deterioracao_rating] = 1
)


// ================================================================
// PASTA: 7. Performance de Limites
// ================================================================

Limite Total =
SUM( vw_stage_cliente_enriquecido[limite_total] )

Limite Utilizado =
SUM( vw_stage_cliente_enriquecido[limite_utilizado] )

Pct Utilizacao Limite Carteira =
DIVIDE( [Limite Utilizado], [Limite Total] )

Qtd Clientes Utilizacao acima 80 =
CALCULATE(
    DISTINCTCOUNT( vw_stage_cliente_enriquecido[cliente_id] ),
    vw_stage_cliente_enriquecido[pct_utilizacao_limite] > 80
)

Qtd Clientes Utilizacao acima 85 =
CALCULATE(
    DISTINCTCOUNT( vw_stage_cliente_enriquecido[cliente_id] ),
    vw_stage_cliente_enriquecido[pct_utilizacao_limite] > 85
)

Headroom Credito =
[Limite Total] - [Limite Utilizado]

Headroom Credito Pct =
1 - [Pct Utilizacao Limite Carteira]

Valor Aprovado Ativo =
SUM( vw_stage_cliente_enriquecido[aprovado_total] )

Taxa Media Carteira =
AVERAGE( vw_stage_cliente_enriquecido[taxa_media] )

Prazo Medio Operacoes Meses =
AVERAGEX(
    FILTER( operacoes, operacoes[status_operacao] = "Ativa" ),
    operacoes[prazo_meses]
)


// ================================================================
// PASTA: 8. Analises Adicionais
// ================================================================

P25 Score =
PERCENTILEX.INC(
    vw_stage_cliente_enriquecido,
    vw_stage_cliente_enriquecido[score_interno],
    0.25
)

P50 Score =
PERCENTILEX.INC(
    vw_stage_cliente_enriquecido,
    vw_stage_cliente_enriquecido[score_interno],
    0.50
)

P75 Score =
PERCENTILEX.INC(
    vw_stage_cliente_enriquecido,
    vw_stage_cliente_enriquecido[score_interno],
    0.75
)

P95 Score =
PERCENTILEX.INC(
    vw_stage_cliente_enriquecido,
    vw_stage_cliente_enriquecido[score_interno],
    0.95
)

Volatilidade Score Mensal =
VAR _serie =
    ADDCOLUMNS(
        VALUES( vw_evolucao_rating_segmento[ano_mes] ),
        "score_mes", CALCULATE( [Score Medio Historico] )
    )
RETURN
    STDEVX.S( _serie, [score_mes] )


// ================================================================
// PASTA: 9. Tempo
// ================================================================

Exposicao Total Mes Anterior =
CALCULATE(
    [Exposicao Total],
    DATEADD( dCalendario[Date], -1, MONTH )
)

Exposicao Variacao MoM =
[Exposicao Total] - [Exposicao Total Mes Anterior]

Exposicao Variacao MoM Pct =
DIVIDE( [Exposicao Variacao MoM], [Exposicao Total Mes Anterior] )

Exposicao Total SPLY =
CALCULATE(
    [Exposicao Total],
    SAMEPERIODLASTYEAR( dCalendario[Date] )
)

Exposicao Variacao YoY Pct =
DIVIDE( [Exposicao Total] - [Exposicao Total SPLY], [Exposicao Total SPLY] )

Exposicao YTD =
CALCULATE(
    [Exposicao Total],
    DATESYTD( dCalendario[Date] )
)

PD Media Mes Anterior Pct =
CALCULATE(
    [PD Media Pct],
    DATEADD( dCalendario[Date], -1, MONTH )
)

PD Variacao MoM pp =
[PD Media Pct] - [PD Media Mes Anterior Pct]


// ================================================================
// PASTA: 10. Status KPI
// ================================================================

Status Exposicao Descoberta =
VAR _pct = [Pct Exposicao Descoberta]
RETURN
    SWITCH(
        TRUE(),
        _pct < 0.30, "META",
        _pct < 0.40, "ATENCAO",
        "CRITICO"
    )

Cor Exposicao Descoberta =
VAR _pct = [Pct Exposicao Descoberta]
RETURN
    SWITCH(
        TRUE(),
        _pct < 0.30, "#1A7F4B",
        _pct < 0.40, "#B45309",
        "#C0392B"
    )

Status Score Medio =
VAR _score = [Score Medio]
RETURN
    SWITCH(
        TRUE(),
        _score >= 850, "EXCELENTE",
        _score >= 800, "MUITO_BOM",
        _score >= 750, "ATENCAO",
        _score >= 650, "CUIDADO",
        "CRITICO"
    )

Cor Score Medio =
VAR _score = [Score Medio]
RETURN
    SWITCH(
        TRUE(),
        _score >= 800, "#1A7F4B",
        _score >= 750, "#B45309",
        _score >= 650, "#EC7000",
        "#C0392B"
    )

Status PD Media =
VAR _pd = [PD Media Pct]
RETURN
    SWITCH(
        TRUE(),
        _pd < 1, "META",
        _pd < 3, "ATENCAO",
        "CRITICO"
    )

Cor PD Media =
VAR _pd = [PD Media Pct]
RETURN
    SWITCH(
        TRUE(),
        _pd < 1, "#1A7F4B",
        _pd < 3, "#B45309",
        "#C0392B"
    )

Status Utilizacao Media =
VAR _pct = DIVIDE( [Utilizacao Media Pct], 100 )
RETURN
    SWITCH(
        TRUE(),
        _pct >= 0.60 && _pct <= 0.75, "IDEAL",
        _pct > 0.85, "ALERTA",
        _pct > 0.75, "ATENCAO",
        "MONITORAR"
    )

Cor Utilizacao Media =
VAR _pct = DIVIDE( [Utilizacao Media Pct], 100 )
RETURN
    SWITCH(
        TRUE(),
        _pct >= 0.60 && _pct <= 0.75, "#1A7F4B",
        _pct > 0.85, "#C0392B",
        _pct > 0.75, "#B45309",
        "#6B7280"
    )

Status Carteira Vencida =
VAR _pct = [Pct Carteira Vencida]
RETURN
    SWITCH(
        TRUE(),
        _pct = 0, "CONTROLE",
        _pct <= 0.01, "ATENCAO",
        "CRITICO"
    )

Cor Carteira Vencida =
VAR _pct = [Pct Carteira Vencida]
RETURN
    SWITCH(
        TRUE(),
        _pct = 0, "#1A7F4B",
        _pct <= 0.01, "#B45309",
        "#C0392B"
    )

Status Top 5 Clientes =
VAR _pct = [Pct Top 5 Clientes]
RETURN
    SWITCH(
        TRUE(),
        _pct <= 0.35, "PULVERIZADO",
        _pct <= 0.45, "MONITORAR",
        "CONCENTRADO"
    )

Cor Top 5 Clientes =
VAR _pct = [Pct Top 5 Clientes]
RETURN
    SWITCH(
        TRUE(),
        _pct <= 0.35, "#1A7F4B",
        _pct <= 0.45, "#B45309",
        "#C0392B"
    )

Label Exposicao MoM =
VAR _var = [Exposicao Variacao MoM Pct]
RETURN
    IF(
        ISBLANK( _var ),
        "-",
        IF(
            _var >= 0,
            "▲ " & FORMAT( _var, "0.0%" ),
            "▼ " & FORMAT( ABS( _var ), "0.0%" )
        )
    )

Label PD MoM =
VAR _var = [PD Variacao MoM pp]
RETURN
    IF(
        ISBLANK( _var ),
        "-",
        IF(
            _var <= 0,
            "▼ " & FORMAT( ABS( _var ), "0.00" ) & "pp",
            "▲ " & FORMAT( _var, "0.00" ) & "pp"
        )
    )
